---
ID: "7c36d111-2b5e-4e2f-b629-ba8d3ae6cfe4"
Parent: "5e10543f-d83e-47a0-b8fe-4c4f667e55c5"
Template: "5e10543f-d83e-47a0-b8fe-4c4f667e55c5"
Path: "/sitecore/templates/Project/skate-park/Page Design Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {5E10543F-D83E-47A0-B8FE-4C4F667E55C5}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ac5280fc-f7d1-4b85-b996-6c5ae57abc2b"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251218T020713Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fa11bffc-2a65-46ac-b5ea-d1c9684de19d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251218T020719Z
