---
ID: "c2e9fba8-e99b-4955-ab5c-31bb75d281bd"
Parent: "c498c887-39db-43ee-a438-a9f604f5df29"
Template: "c498c887-39db-43ee-a438-a9f604f5df29"
Path: "/sitecore/templates/Project/skate-park/Skate Park Templates/Skateboard/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251218T045812Z
    - ID: "2d117de9-03b8-4cb2-ad29-0d4590106a3b"
      Hint: Material
      Value: Bamboo
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e4185e91-cd8b-470e-b15e-ecb684c70043"
    - ID: "9ecf91ea-a3af-4631-a7b4-d74112236e57"
      Hint: Content
      Value: |
        <p style="margin: 0in;">Looking for a skateboard that can keep up with your shredding skills? The $name is here to take your skating to the next level.<span>&nbsp; </span>Whether you're hitting the skatepark or cruising the streets, the $name is the perfect board for you.</p>
        <p style="margin: 0in;">&nbsp;</p>
        <p style="margin: 0in;">Ready to take your skating to the next level? Order your $name today!</p>
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\niwamoto@tech.softbank.co.jp
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251218T050657Z
